language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
script:
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
notifications:
  email:
    - avdeevvladimir@gmail.com
